[package]
name = "repocopy"
version = "0.2.0"
edition = "2021"

[dependencies]
walkdir = "2.5.0"
arboard = "3.4.1"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
clap = { version = "4.5", features = ["derive"] }
dirs = "5.0"
quick-xml = "0.34"
xdg = "2.5"
